### ISSUE TITLE
Problems with large window size

### ISSUE THREAD

**Issue by lightonflux** [jorchube/monitorets#47]
![image](https://user-images.githubusercontent.com/1377943/213931433-e85fafc9-5f15-4686-a113-93acb19c21e5.png)

This does not look intentional.

I suggest either increasing/removing the max size for the monitors, or setting a max size for the window. It depends a bit on the scope of use that you intend for this application. 

Personally, i would prefer it if the monitors scale to the max of the window. This way you can temporarily use them to monitor something from far away (distance to monitor), similar to the graph mode of windows task manager (double click on a graph) or gnome-system-monitor with collapsed graphs. 

![image](https://user-images.githubusercontent.com/1377943/213931591-768191bc-836a-4200-ae83-2e1235e30917.png)

**Comment by jorchube** [comment]
Hello!

I see. I did not imagine this use case. It is interesting.

Truth be told, limiting the size of the monitors is intentional but it is meant to be a temporary solution until I solve some technical details. So the idea is to have an unlimited monitor size, just because the actual limit is totally arbitrary and serves no purpose.

So yeah, this is something I want to address. ;)

**Comment by jorchube** [comment]
Closing this as version 0.9.0 fixes it.
