### ISSUE TITLE
Increase minimal height

### ISSUE THREAD

**Issue by lightonflux** [jorchube/monitorets#5]
Current minimal height is to low:
![Bildschirmfoto vom 2022-11-04 20-31-43](https://user-images.githubusercontent.com/1377943/200060048-bf84b77f-7bb4-4885-8dc2-0c161b9c7aff.png)

Currently, the minimal height for the window means that the user can decrease the size in a way make the app look ugly and hard to read the labels or graphs. It is even possible to reduce the size to a height that makes it impossible to see any data:

![Bildschirmfoto vom 2022-11-04 20-33-48](https://user-images.githubusercontent.com/1377943/200060297-1475eb3d-3237-461e-8764-ebbb7e9e5f2a.png)

It would look nicer if the minimal height would make sure that all labels are readable plus a bit of extra space, so the padding looks right.  Something like this:
![Bildschirmfoto vom 2022-11-04 20-31-35](https://user-images.githubusercontent.com/1377943/200060008-4947940e-6ab6-4e6a-8623-7aa4b9d92613.png)

**Comment by jorchube** [comment]
Hello!

I think that you are right. However I am thinking on taking a different approach, not just setting a minimum window height:

It is hard (impossible?) to pick an adequate minimum size (both height and width) because that constraint depends on the number of monitors enabled and the layout. Instead, I am going to try setting a minimum monitor size to ensure that no matter how many monitors are enabled (there are more coming ;)) the data will be readable.

A beta version with this will come soon.

**Comment by jorchube** [comment]
Version 0.3.0 is out addressing this.
