### ISSUE TITLE
Keyboard shortcut for settings

### ISSUE THREAD

**Issue by gregorni** [jorchube/monitorets#59]
There should be a keyboard shortcut to easily access the preferences window. I would suggest `Ctrl`+`,`.

**Comment by gregorni** [comment]
This would also mean we would need an extra "shortcuts" page.

**Comment by jorchube** [comment]
Hello!

Thank you for opening this issue and the associated Pull Request: It is a very nice one!

I don't know if you have noticed, but the linting check of the PR has failed.

If you don't want to correct it, I can just add the change myself. Otherwise, If you prefer to update your PR running the linter you can do it by configuring a development environment by running

```bash
make install-dev-requirements
```
 then entering a shell in that environment

```bash
make dev-shell
```
and then run the linter

```bash
make linting
```

or to just check the linter rules without modifying the code you can run

```bash
make check-linting
```

Or you can do it by any other means you want. 


Anyway, let me know if you prefer to update your PR or if I shall apply the changes myself :)


Thank you very much!

**Comment by gregorni** [comment]
Thanks for the detailed instructions! I fixed it now. The workflows are still pending, so we'll have to see if all checks pass.

**Comment by jorchube** [comment]
The PR is more than ready! :rocket: 
Thank you very much!
